"""Per-(place, person) blurbs for the "People connected to <Place>" section
of each place page (data/places/<id>.html), mirroring the per-member `role`
text on the New Testament church pages.

Shape:
    ROLES = { place_id: { person_id: (role, [references]) } }

`role` is a short, lowercase-start phrase saying what Scripture ties this
person to this place (an action, words, an episode) -- grounded in the
person's own documented story, never invented (see CLAUDE.md's Factual
Accuracy rules). `references` is one or two chapter:verse citations for that
tie (no verse text -- references only, per CLAUDE.md's Bible Version
Handling).

Consumed by generate_places.py (which attaches role/references onto each
place's related_people entries and warns on any person_id that isn't a
full-tier person at that place). Not committed via .gitignore's _build/ rule
but force-added, same pattern as places_data.py and the backfill_*.py
scripts.

The seven largest places (Jerusalem, Samaria, the two kingdoms, Egypt,
Canaan, Babylon) are deliberately capped: only their most narratively
significant figures get a blurb here, and generate_static_site.py renders
the remainder as a plain "Also named in Scripture at <place>" list. Every
other full place aims to cover all of its named people.
"""

ROLES = {
    # ---- one- and two-person places ----
    "ai": {
        "achan": ("kept plunder devoted to destruction from Jericho, bringing Israel's rout here", ["Joshua 7:1-5"]),
    },
    "arimathea": {
        "joseph-7": ("the council member of this town who gave Jesus his own new tomb", ["Matthew 27:57-60"]),
    },
    "ashdod": {
        "sargon": ("Assyria's king, whose capture of this Philistine city framed Isaiah's barefoot sign", ["Isaiah 20:1"]),
    },
    "athens": {
        "damaris": ("a woman who believed after Paul's address at the Areopagus", ["Acts 17:34"]),
        "dionysius": ("a member of the Areopagus council who believed Paul's message", ["Acts 17:34"]),
    },
    "baal-peor": {
        "phinehas": ("struck down Zimri and Cozbi at the height of Israel's idolatry here, stopping the plague", ["Numbers 25:7-8"]),
    },
    "cana": {
        "nathanael": ("a Galilean of this town, won over when Jesus showed supernatural knowledge of him", ["John 21:2", "John 1:47-49"]),
    },
    "cave-of-machpelah": {
        "ephron": ("the Hittite who sold Abraham this cave as a burial place for Sarah", ["Genesis 23:8-17"]),
    },
    "crete": {
        "titus": ("left here by Paul to appoint elders in every town", ["Titus 1:5"]),
        "tychicus": ("one of two men Paul considered sending to relieve Titus here", ["Titus 3:12"]),
    },
    "dan": {
        "jonathan-2": ("the wandering Levite who became priest for the tribe's idol here", ["Judges 18:30"]),
        "micah": ("the Ephraimite whose stolen idol and hired priest the Danites carried off and set up here", ["Judges 18:27-31"]),
    },
    "emmaus": {
        "cleopas": ("one of two disciples who recognized the risen Jesus at table on the road here", ["Luke 24:18", "Luke 24:30-31"]),
    },
    "gaza": {
        "samson": ("carried off the city gates by night, and later died pulling down its temple", ["Judges 16:3", "Judges 16:29-30"]),
    },
    "gethsemane": {
        "malchus": ("the high priest's servant whose severed ear Jesus healed at the arrest here", ["John 18:10"]),
    },
    "gomorrah": {
        "birsha": ("its king, defeated with the allied kings of the plain in the Valley of Siddim", ["Genesis 14:2", "Genesis 14:8-10"]),
    },
    "hazor": {
        "jabin": ("a king of this city, defeated by Joshua and, later, under Deborah and Barak", ["Joshua 11:1", "Judges 4:2"]),
    },
    "jabesh-gilead": {
        "nahash": ("the Ammonite king whose siege of this town roused Saul to his first victory", ["1 Samuel 11:1-11"]),
    },
    "joppa": {
        "simon-6": ("the tanner in whose house by the sea Peter lodged and saw the vision of the sheet", ["Acts 10:6", "Acts 10:9-16"]),
        "tabitha": ("a disciple full of good works whom Peter raised from the dead here", ["Acts 9:36-41"]),
    },
    "kir-hareseth": {
        "mesha": ("Moab's king, besieged here, who sacrificed his own firstborn son on the wall", ["2 Kings 3:26-27"]),
    },
    "land-of-nod": {
        "cain": ("settled here as a restless wanderer after murdering his brother Abel", ["Genesis 4:16"]),
    },
    "laodicea": {
        "nympha": ("hosted a house church that Paul greets in the letter to the Colossians", ["Colossians 4:15"]),
    },
    "magdala": {
        "mary-magdalene": ("the town's daughter, freed by Jesus from seven demons and first witness of the resurrection", ["Luke 8:2", "Mark 16:9"]),
    },
    "malta": {
        "julius": ("the centurion who spared the prisoners after the shipwreck on this island", ["Acts 27:42-44"]),
        "publius": ("the island's chief man, whose father Paul healed of fever and dysentery", ["Acts 28:7-8"]),
    },
    "megiddo": {
        "josiah": ("Judah's reforming king, mortally wounded in battle against Pharaoh Neco here", ["2 Kings 23:29-30"]),
        "pharaoh-neco": ("Egypt's king, who killed King Josiah in battle here", ["2 Chronicles 35:20-24"]),
    },
    "mount-carmel": {
        "elijah": ("called down fire from heaven and defeated the 450 prophets of Baal on this mountain", ["1 Kings 18:19-40"]),
    },
    "mount-gerizim": {
        "jotham": ("shouted his parable of the trees from this mountain over Shechem", ["Judges 9:7"]),
    },
    "patmos": {
        "john-2": ("exiled to this island, where he received the visions of Revelation", ["Revelation 1:9"]),
    },
    "pergamum": {
        "antipas": ("Christ's “faithful witness,” put to death in this city", ["Revelation 2:13"]),
    },
    "region-of-the-gerasenes": {
        "legion": ("the name of the demons Jesus cast out of a man here and sent into the pigs", ["Mark 5:9-13"]),
    },
    "salem": {
        "melchizedek": ("its king and priest of God Most High, who blessed Abram and received his tithe", ["Genesis 14:18-20"]),
    },
    "shittim": {
        "cozbi": ("the Midianite woman brought into the camp here and struck down by Phinehas", ["Numbers 25:6-8", "Numbers 25:15"]),
    },
    "sodom": {
        "bera": ("king of this city, defeated in the war of the four kings and met by Abram afterward", ["Genesis 14:2", "Genesis 14:17-21"]),
        "lot": ("chose to settle in this city, and was dragged out by angels the night it was destroyed", ["Genesis 13:12", "Genesis 19:15-16"]),
    },
    "thebez": {
        "abimelech-2": ("died besieging this town when a woman dropped a millstone on his head", ["Judges 9:50-54"]),
    },
    "thyatira": {
        "jezebel-2": ("Christ's name for the false prophetess tolerated in the church here", ["Revelation 2:20"]),
        "lydia": ("a dealer in this city's purple cloth, converted under Paul's preaching at Philippi", ["Acts 16:14"]),
    },
    "valley-of-achor": {
        "achan": ("stoned in this valley for taking devoted plunder from Jericho", ["Joshua 7:24-26"]),
    },
    "valley-of-sorek": {
        "delilah": ("the woman Samson loved here, bribed to pry out the secret of his strength", ["Judges 16:4-5"]),
    },
    "wilderness-of-judea": {
        "john": ("preached repentance and baptized here, preparing the way for Jesus", ["Matthew 3:1-6"]),
    },

    # ---- three-person places ----
    "ararat": {
        "noah": ("the ark came to rest on these mountains as the flood receded", ["Genesis 8:4"]),
        "adrammelech": ("fled to this land after murdering his father Sennacherib", ["2 Kings 19:37"]),
        "sharezer": ("fled here with his brother after murdering their father Sennacherib", ["2 Kings 19:37"]),
    },
    "bahurim": {
        "ahimaaz-2": ("hid in a well in this town from Absalom's pursuers while carrying word to David", ["2 Samuel 17:17-20"]),
        "palti-2": ("followed his wife Michal weeping as far as this town when David reclaimed her", ["2 Samuel 3:15-16"]),
        "shimei-2": ("cursed and threw stones at David as he passed through here in flight", ["2 Samuel 16:5-13"]),
    },
    "bethany": {
        "lazarus-2": ("raised by Jesus here after four days in the tomb", ["John 11:1", "John 11:43-44"]),
        "martha": ("welcomed Jesus into her home here and confessed Him at Lazarus's tomb", ["Luke 10:38", "John 11:20-27"]),
        "mary-2": ("sat at Jesus's feet here and anointed them with costly perfume", ["Luke 10:39", "John 12:3"]),
    },
    "gath": {
        "achish": ("its Philistine king, who twice sheltered the fugitive David", ["1 Samuel 21:10-14", "1 Samuel 27:2-6"]),
        "goliath": ("the Philistine champion from this city, killed by David in the Valley of Elah", ["1 Samuel 17:4", "1 Samuel 17:23"]),
    },
    "haran": {
        "abraham": ("settled here with Terah, then left at God's call for Canaan", ["Genesis 11:31", "Genesis 12:4"]),
        "bethuel": ("an Aramean of this region who consented to Rebekah's marriage to Isaac", ["Genesis 24:50"]),
        "sarah": ("left this city with Abraham for the land God promised", ["Genesis 11:31", "Genesis 12:5"]),
    },
    "kadesh-barnea": {
        "ammiel": ("the spy from the tribe of Dan who brought back a fearful report of Canaan", ["Numbers 13:12"]),
        "caleb": ("urged Israel from here to go up and take the land, and was promised Hebron", ["Numbers 13:30", "Numbers 14:24"]),
        "igal": ("the spy from the tribe of Issachar who joined the fearful report of the land", ["Numbers 13:7"]),
    },
    "karkor": {
        "jether": ("Gideon's firstborn, too afraid to execute the captured Midianite kings", ["Judges 8:20"]),
        "zalmunna": ("a Midianite king captured by Gideon after the rout of his army near here", ["Judges 8:10-12", "Judges 8:21"]),
        "zebah": ("a Midianite king captured by Gideon after the rout of his army near here", ["Judges 8:10-12", "Judges 8:21"]),
    },
    "kiriath-jearim": {
        "abinadab": ("kept the ark of the covenant in his house here for about twenty years", ["1 Samuel 7:1-2"]),
        "ahio": ("walked before the ark as it left his father's house here", ["2 Samuel 6:3-4"]),
        "eleazar-2": ("consecrated to guard the ark in his father Abinadab's house here", ["1 Samuel 7:1"]),
    },
    "lo-debar": {
        "machir-2": ("sheltered the crippled Mephibosheth here before David sent for him", ["2 Samuel 9:4-5"]),
        "mephibosheth": ("living here in obscurity when David summoned him to the king's table", ["2 Samuel 9:4-7"]),
        "ziba": ("Saul's servant who told David that Mephibosheth was staying here", ["2 Samuel 9:2-4"]),
    },
    "lystra": {
        "eunice": ("Timothy's mother, a believing woman of this town", ["Acts 16:1", "2 Timothy 1:5"]),
        "lois": ("Timothy's grandmother, in whose household sincere faith took root", ["2 Timothy 1:5"]),
        "timothy": ("the disciple of this town, well spoken of, whom Paul took as a companion", ["Acts 16:1-3"]),
    },
    "mount-gilboa": {
        "abinadab-2": ("one of Saul's sons, killed with him in the battle on this mountain", ["1 Samuel 31:2"]),
        "jonathan": ("Saul's son and David's friend, killed alongside his father here", ["1 Samuel 31:2"]),
        "malchi-shua": ("one of Saul's sons, killed with him in the battle on this mountain", ["1 Samuel 31:2"]),
    },
    "mount-tabor": {
        "barak": ("mustered ten thousand men on this mountain before routing Sisera", ["Judges 4:6", "Judges 4:14"]),
        "deborah-2": ("sent Barak down from this mountain against Sisera's army", ["Judges 4:6", "Judges 4:14"]),
        "sisera": ("his chariots were drawn to the Kishon below this mountain and destroyed", ["Judges 4:14-15"]),
    },
    "nob": {
        "abiathar": ("the sole priest of this town to escape Saul's massacre, fleeing to David", ["1 Samuel 22:20"]),
        "ahimelech": ("the priest here who fed the fugitive David and gave him Goliath's sword", ["1 Samuel 21:1-9"]),
        "doeg": ("reported the priests of this town to Saul, then carried out their massacre", ["1 Samuel 22:9-18"]),
    },
    "ophrah": {
        "gideon": ("called by the angel of the LORD at this town, where he tore down Baal's altar", ["Judges 6:11", "Judges 6:25-27"]),
        "joash": ("owned the altar of Baal here and defended his son Gideon before the townsmen", ["Judges 6:25-31"]),
        "jotham": ("Gideon's youngest son, the lone survivor of Abimelech's massacre here", ["Judges 9:5"]),
    },
    "penuel": {
        "israel": ("wrestled with God through the night here and was renamed Israel", ["Genesis 32:24-31"]),
        "zalmunna": ("a Midianite king whom Gideon pursued past this town", ["Judges 8:8-12"]),
        "zebah": ("a Midianite king whom Gideon pursued past this town", ["Judges 8:8-12"]),
    },
    "philistine-territory": {
        "samson": ("raided and judged among the Philistines for twenty years", ["Judges 15:20"]),
        "saph": ("a Philistine giant killed by David's man Sibbecai", ["2 Samuel 21:18"]),
        "shamgar": ("struck down six hundred Philistines with an ox goad", ["Judges 3:31"]),
    },
    "ramathaim-zophim": {
        "elkanah-2": ("the Ephraimite of this town, husband of Hannah and Peninnah", ["1 Samuel 1:1"]),
        "hannah": ("of this town, whose vow at Shiloh brought the birth of Samuel", ["1 Samuel 1:1-2", "1 Samuel 1:19-20"]),
        "peninnah": ("Elkanah's other wife of this town, who provoked the barren Hannah", ["1 Samuel 1:2-7"]),
    },
    "riblah": {
        "jehoahaz-2": ("Judah's king, put in chains here by Pharaoh Neco", ["2 Kings 23:33"]),
        "seraiah-2": ("Jerusalem's chief priest, executed here by the king of Babylon", ["2 Kings 25:18-21"]),
        "zedekiah-2": ("Judah's last king, blinded here after his sons were killed before him", ["2 Kings 25:6-7"]),
    },
    "timnah": {
        "hirah": ("Judah's Adullamite friend, who went with him to the sheepshearing near here", ["Genesis 38:12"]),
        "samson": ("went down to this town for a Philistine wife and killed a lion on the way", ["Judges 14:1-6"]),
        "tamar": ("sat veiled by the road to this town and conceived twins by Judah", ["Genesis 38:14"]),
    },
    "transjordan": {
        "gideon": ("pursued the fleeing Midianite kings across the Jordan into this region", ["Judges 8:4-12"]),
        "jeriah": ("set by David over the Reubenites, Gadites, and half-Manasseh east of the Jordan", ["1 Chronicles 26:31-32"]),
        "sihon": ("the Amorite king whose land east of the Jordan Israel took after he attacked them", ["Numbers 21:21-31"]),
    },
    "tyre": {
        "blastus": ("Herod's chamberlain, whose favor the people of this city sought for peace", ["Acts 12:20"]),
        "hiram-2": ("the bronze craftsman of this city brought to cast the temple's pillars", ["1 Kings 7:13-14"]),
        "hiram": ("its king, who supplied cedar and craftsmen for David's and Solomon's building", ["1 Kings 5:1-10"]),
    },
    "ur-of-the-chaldeans": {
        "abraham": ("left this city with his father Terah at the start of the journey to Canaan", ["Genesis 11:31"]),
        "lot": ("set out from this city with his grandfather Terah and his uncle Abram", ["Genesis 11:31"]),
        "sarah": ("left this city with Abram and Terah for the land of Canaan", ["Genesis 11:31"]),
    },
    "valley-of-elah": {
        "abinadab-3": ("David's brother, serving in Saul's army here during the standoff with Goliath", ["1 Samuel 17:13"]),
        "eliab-3": ("David's eldest brother, who rebuked him for coming to the battle line here", ["1 Samuel 17:28"]),
        "goliath": ("defied Israel's army in this valley for forty days until David killed him", ["1 Samuel 17:2-4", "1 Samuel 17:49"]),
    },
    "zoar": {
        "ammon": ("conceived by Lot's younger daughter in the hills above this town", ["Genesis 19:30-38"]),
        "lot": ("fled here from Sodom, then went up in fear to the hills nearby", ["Genesis 19:20-30"]),
        "moab": ("conceived by Lot's older daughter in the hills above this town", ["Genesis 19:30-37"]),
    },

    # ---- four- and five-person places ----
    "capernaum": {
        "andrew": ("Peter's brother, a fisherman whose home was in this town", ["Mark 1:29"]),
        "jairus": ("a synagogue official of this town whose dying daughter Jesus raised", ["Mark 5:22-42"]),
        "matthew": ("sat at the tax booth here until Jesus called him to follow", ["Mark 2:14", "Matthew 9:9"]),
        "peter": ("the fisherman whose house here Jesus made a base for His Galilean ministry", ["Mark 1:21", "Mark 1:29"]),
    },
    "colossae": {
        "archippus": ("charged through the church here to complete the ministry he had received", ["Colossians 4:17"]),
        "epaphras": ("a native of this city, who first brought it the gospel and prayed hard for it", ["Colossians 1:7", "Colossians 4:12"]),
        "onesimus": ("the runaway slave of this city, sent back with Paul's letter to Philemon", ["Colossians 4:9", "Philemon 1:10"]),
        "philemon": ("a believer of this city to whom Paul wrote about his slave Onesimus", ["Philemon 1:1-2"]),
    },
    "garden-of-eden": {
        "adam": ("formed by God and placed here to work and keep the garden", ["Genesis 2:8", "Genesis 2:15"]),
        "eve": ("formed from Adam's side here and deceived by the serpent", ["Genesis 2:22", "Genesis 3:1-6"]),
        "cain": ("born to Adam and Eve after their expulsion from the garden", ["Genesis 3:24", "Genesis 4:1"]),
        "abel": ("second son of Adam and Eve, born after the expulsion from the garden", ["Genesis 4:2"]),
    },
    "gob": {
        "elhanan": ("killed the Gittite giant Lahmi in the fighting here", ["1 Chronicles 20:5", "2 Samuel 21:19"]),
        "jonathan-4": ("David's nephew, who killed a taunting giant of Gath in battle here", ["2 Samuel 21:21"]),
        "saph": ("a Philistine giant killed by Sibbecai in the fighting here", ["2 Samuel 21:18"]),
        "sibbecai": ("one of David's men, who struck down the giant Saph here", ["2 Samuel 21:18"]),
    },
    "hill-country-of-ephraim": {
        "deborah-2": ("judged Israel under her palm in this hill country", ["Judges 4:5"]),
        "ehud": ("sounded the trumpet in these hills to rally Israel after killing Eglon", ["Judges 3:27"]),
        "jonathan-2": ("the Levite hired by Micah in these hills before going to Dan", ["Judges 17:7-12"]),
        "micah": ("the Ephraimite of these hills who made an idol and a shrine", ["Judges 17:1-5"]),
    },
    "jordan-river": {
        "chimham": ("Barzillai's son, whom David took across this river with him", ["2 Samuel 19:37-40"]),
        "elisha": ("took up Elijah's fallen mantle and parted this river to cross back", ["2 Kings 2:13-14"]),
        "john": ("baptized in this river, including the baptism of Jesus", ["Matthew 3:6", "Matthew 3:13"]),
        "naaman": ("washed seven times in this river at Elisha's word and was healed", ["2 Kings 5:14"]),
    },
    "makkedah": {
        "adoni-zedek": ("king of Jerusalem, caught in a cave here and executed by Joshua", ["Joshua 10:16-26"]),
        "debir": ("king of Eglon, executed with the coalition kings at this town", ["Joshua 10:3", "Joshua 10:23-26"]),
        "hoham": ("king of Hebron, executed with the coalition kings at this town", ["Joshua 10:3", "Joshua 10:23-26"]),
        "piram": ("king of Jarmuth, executed with the coalition kings at this town", ["Joshua 10:3", "Joshua 10:23-26"]),
    },
    "mesopotamia": {
        "enoch": ("in the line of Seth, who walked with God and was taken without dying", ["Genesis 5:22-24"]),
        "ham": ("a son of Noah who came through the flood", ["Genesis 7:13"]),
        "lamech": ("in the line of Cain, who boasted of sevenfold vengeance", ["Genesis 4:23-24"]),
        "methuselah": ("grandfather of Noah and the longest-lived man in Scripture", ["Genesis 5:27"]),
    },
    "persia": {
        "artaxerxes": ("its king, who sent Ezra and later Nehemiah to Jerusalem", ["Ezra 7:11-13", "Nehemiah 2:1-8"]),
        "cyrus": ("its king, who decreed the exiles' return to rebuild the temple", ["Ezra 1:1-4"]),
        "darius": ("its king, who confirmed Cyrus's decree and funded the temple's completion", ["Ezra 6:1-12"]),
        "mithredath": ("Cyrus's treasurer, who counted out the temple vessels for the return", ["Ezra 1:8"]),
    },
    "philippi": {
        "epaphroditus": ("sent by this church with a gift to Paul, and fell dangerously ill in the service", ["Philippians 2:25-30"]),
        "euodia": ("a woman who labored with Paul in this church, urged to be reconciled with Syntyche", ["Philippians 4:2-3"]),
        "lydia": ("the seller of purple whose household was the first baptized here", ["Acts 16:14-15"]),
        "silas": ("beaten and jailed with Paul here, then freed by an earthquake", ["Acts 16:19-26"]),
    },
    "rabbah": {
        "hanun": ("Ammon's king, who humiliated David's envoys and drew Israel to besiege this city", ["2 Samuel 10:1-4"]),
        "joab": ("led the siege of this city and summoned David for its capture", ["2 Samuel 12:26-28"]),
        "uriah": ("set at the fiercest point of the fighting at this city and killed", ["2 Samuel 11:16-17"]),
        "shobi": ("an Ammonite of this royal city who later brought supplies to David", ["2 Samuel 17:27-29"]),
    },
    "ammon": {
        "baalis": ("its king, who sent Ishmael to assassinate the governor Gedaliah", ["Jeremiah 40:14"]),
        "ishmael-2": ("took refuge with this people after killing Gedaliah", ["Jeremiah 41:10", "Jeremiah 41:15"]),
        "jephthah": ("delivered Israel from this nation's oppression", ["Judges 11:32-33"]),
        "nahash": ("its king, whose siege of Jabesh-gilead roused Saul", ["1 Samuel 11:1-2"]),
        "tobiah": ("an official of this people who mocked and schemed against Nehemiah's wall", ["Nehemiah 2:10", "Nehemiah 2:19"]),
    },
    "cyprus": {
        "bar-jesus": ("the sorcerer of this island struck blind for opposing Paul", ["Acts 13:6-11"]),
        "barnabas": ("a Levite of this island, who led the first mission through it", ["Acts 4:36", "Acts 13:4-5"]),
        "mark": ("assisted Paul and Barnabas as they crossed this island", ["Acts 13:5"]),
        "mnason": ("a disciple of this island of long standing, who hosted Paul", ["Acts 21:16"]),
        "sergius-paulus": ("the island's proconsul, who believed after Elymas was struck blind", ["Acts 13:7-12"]),
    },
    "edom": {
        "amaziah": ("Judah's king, who defeated this nation and then took up its gods", ["2 Chronicles 25:11-14"]),
        "esau": ("Isaac's elder son, who settled in Seir and fathered this nation", ["Genesis 36:8-9"]),
        "hadad-4": ("a prince of this nation, raised up as an adversary against Solomon", ["1 Kings 11:14"]),
        "jehoram": ("Judah's king, in whose reign this nation revolted from Judah's rule", ["2 Kings 8:20-22"]),
        "obadiah-12": ("prophesied this nation's downfall for gloating over Jerusalem's fall", ["Obadiah 1:10-15"]),
    },
    "gerar": {
        "abimelech": ("the city's king, who took Sarah and later made a covenant of peace with Abraham", ["Genesis 20:2-15", "Genesis 21:22-32"]),
        "ahuzzath": ("the king's adviser, who came to make a covenant with Isaac here", ["Genesis 26:26"]),
        "isaac": ("settled here in a famine, prospered, and reopened his father's wells", ["Genesis 26:1-22"]),
        "phicol": ("the king's army commander, who made covenants here with Abraham and Isaac", ["Genesis 21:22", "Genesis 26:26"]),
        "rebekah": ("whom Isaac called his sister here for fear of the men of the place", ["Genesis 26:7"]),
    },
    "gilgal": {
        "agag-2": ("the Amalekite king whom Samuel executed before the LORD here", ["1 Samuel 15:33"]),
        "chimham": ("escorted King David from here after Absalom's revolt", ["2 Samuel 19:40"]),
        "ehud": ("turned back from the carved images near here to kill Eglon", ["Judges 3:19"]),
        "elisha": ("at the prophets' community here, purified the poisoned stew", ["2 Kings 4:38-41"]),
        "samuel": ("judged Israel on the yearly circuit that included this town", ["1 Samuel 7:16"]),
    },
    "judea": {
        "archelaus": ("the harsh ruler of this region whom Joseph avoided, settling in Nazareth instead", ["Matthew 2:22"]),
        "judas-2": ("betrayed Jesus to the authorities of this region for thirty pieces of silver", ["Matthew 26:14-16"]),
        "pilate": ("Rome's governor of this region, who sentenced Jesus to death", ["Luke 3:1", "Luke 23:24"]),
        "thomas": ("urged the disciples to go with Jesus back into this region despite the danger", ["John 11:7-16"]),
    },
    "lachish": {
        "amaziah": ("Judah's king, killed by conspirators after fleeing to this city", ["2 Kings 14:19"]),
        "horam": ("king of Gezer, who came to help this city and was destroyed by Joshua", ["Joshua 10:33"]),
        "japhia": ("this city's king, one of the five executed by Joshua at Makkedah", ["Joshua 10:3", "Joshua 10:23-26"]),
        "rabshakeh": ("Sennacherib's officer, sent from this city to demand Jerusalem's surrender", ["2 Kings 18:17"]),
        "sennacherib": ("besieged this fortified city on his campaign against Judah", ["2 Kings 18:14", "2 Kings 18:17"]),
    },
    "nazareth": {
        "gabriel": ("sent to this town to announce to Mary the birth of Jesus", ["Luke 1:26-33"]),
        "james-3": ("a brother of Jesus, raised in this town", ["Matthew 13:55", "Mark 6:3"]),
        "joseph-6": ("the carpenter of this town, betrothed to Mary", ["Matthew 13:55", "Luke 2:4"]),
        "judas-3": ("a brother of Jesus, raised in this town", ["Mark 6:3"]),
        "mary": ("the young woman of this town who conceived Jesus by the Holy Spirit", ["Luke 1:26-31"]),
    },
    "nineveh": {
        "adrammelech": ("murdered his father Sennacherib in this city and fled", ["2 Kings 19:36-37"]),
        "jonah": ("sent to preach to this city, which repented at his message", ["Jonah 3:3-5"]),
        "nahum": ("prophesied the fall of this city", ["Nahum 1:1", "Nahum 3:7"]),
        "sennacherib": ("Assyria's king, who withdrew to this city and was murdered there by his sons", ["2 Kings 19:36-37"]),
        "sharezer": ("murdered his father Sennacherib in this city and fled", ["2 Kings 19:37"]),
    },
    "uz": {
        "elihu-5": ("the young man who rebuked Job and his three friends before the LORD spoke", ["Job 32:2-6"]),
        "jemimah": ("the eldest of Job's daughters, born after the LORD restored him here", ["Job 42:14"]),
        "job": ("the blameless man of this land who lost everything and was restored twofold", ["Job 1:1-3", "Job 42:10-12"]),
        "keren-happuch": ("the youngest of Job's daughters, born after the LORD restored him here", ["Job 42:14"]),
        "keziah": ("the second of Job's daughters, born after the LORD restored him here", ["Job 42:14"]),
    },
    "valley-of-siddim": {
        "arioch": ("king of Ellasar, in the eastern coalition that fought here", ["Genesis 14:1-9"]),
        "bera": ("king of Sodom, defeated in the battle here", ["Genesis 14:8-10"]),
        "birsha": ("king of Gomorrah, defeated in the battle here", ["Genesis 14:8-10"]),
        "chedorlaomer": ("king of Elam, who led the coalition to victory here and carried off Lot", ["Genesis 14:9-12"]),
        "shemeber": ("king of Zeboiim, defeated in the battle here", ["Genesis 14:2", "Genesis 14:8-10"]),
    },

    # ---- six- and seven-person places ----
    "aram": {
        "ben-hadad": ("a king of this land, who warred with and besieged Israel", ["1 Kings 20:1"]),
        "ben-hadad-2": ("Hazael's son and its king, from whom Israel recovered lost towns", ["2 Kings 13:24-25"]),
        "hadadezer": ("king of Zobah in this region, defeated by David toward the Euphrates", ["2 Samuel 8:3"]),
        "hazael": ("anointed at God's word to be its king, and a long oppressor of Israel", ["1 Kings 19:15", "2 Kings 8:12-15"]),
        "naaman-2": ("commander of this land's army, healed of leprosy by Elisha in Israel", ["2 Kings 5:1-14"]),
        "rezin": ("its king, who allied with Israel against Judah before Assyria killed him", ["2 Kings 16:5-9"]),
    },
    "asia-minor": {
        "demetrius-2": ("a believer of this region, well spoken of by everyone", ["3 John 1:12"]),
        "diotrephes": ("a church leader of this region who rejected the apostle John's authority", ["3 John 1:9-10"]),
        "gaius-3": ("the believer of this region John commended for his hospitality", ["3 John 1:1-8"]),
        "paul": ("evangelized much of this region on his missionary journeys", ["Acts 16:6", "Acts 19:10"]),
        "phygelus": ("one of the believers of this region who turned away from Paul", ["2 Timothy 1:15"]),
        "tychicus": ("of this region, a trusted courier of Paul's letters to its churches", ["Colossians 4:7", "Ephesians 6:21"]),
    },
    "assyria": {
        "esarhaddon": ("its king, who resettled foreign peoples in Samaria", ["Ezra 4:2"]),
        "osnappar": ("its king, credited with deporting peoples and resettling them in Samaria", ["Ezra 4:10"]),
        "sargon": ("its king, whose commander captured Ashdod", ["Isaiah 20:1"]),
        "sennacherib": ("its king, who besieged Jerusalem and lost 185,000 troops in a night", ["2 Kings 19:35-36"]),
        "shalmaneser": ("its king, who besieged Samaria and exiled the northern tribes", ["2 Kings 17:3-6"]),
        "tiglath-pileser": ("its king, who deported northern Israel and was bribed by Ahaz", ["2 Kings 15:29", "2 Kings 16:7-9"]),
    },
    "beersheba": {
        "abijah": ("Samuel's son, a corrupt judge stationed at this town", ["1 Samuel 8:1-3"]),
        "isaac": ("dug a well and met the LORD here, who confirmed the covenant promise", ["Genesis 26:23-25"]),
        "israel": ("offered sacrifices here on his way down to Egypt, and God spoke to him", ["Genesis 46:1-4"]),
        "joel": ("Samuel's firstborn, a corrupt judge stationed at this town", ["1 Samuel 8:1-3"]),
        "phicol": ("Abimelech's commander, who made a covenant with Abraham at this well", ["Genesis 21:31-32"]),
        "rebekah": ("wife of Isaac, living here when Jacob deceived Isaac and fled", ["Genesis 28:10"]),
    },
    "gibeah": {
        "jonathan": ("Saul's son, who struck the Philistine garrison from his father's town here", ["1 Samuel 13:2-3"]),
        "kish": ("Saul's father, whose lost donkeys sent Saul from this town to Samuel", ["1 Samuel 9:1-3"]),
        "mephibosheth-2": ("a son of Saul, handed to the Gibeonites and hanged at this town", ["2 Samuel 21:6", "2 Samuel 21:8-9"]),
        "michal": ("Saul's daughter of this town, who lowered David from a window to escape", ["1 Samuel 19:11-17"]),
        "rizpah": ("Saul's concubine, who kept vigil over her hanged sons at this town", ["2 Samuel 21:8-10"]),
        "saul": ("Israel's first king, who ruled from this, his hometown", ["1 Samuel 10:26", "1 Samuel 15:34"]),
    },
    "jezreel": {
        "ahab": ("kept a palace here, beside Naboth's vineyard", ["1 Kings 21:1"]),
        "ahinoam-2": ("a wife of David, from this town", ["1 Samuel 25:43"]),
        "bidkar": ("Jehu's officer, who threw King Joram's body onto Naboth's plot here", ["2 Kings 9:25-26"]),
        "jehu-2": ("killed King Joram here and had Jezebel thrown from a window in this town", ["2 Kings 9:24", "2 Kings 9:30-33"]),
        "jezebel": ("thrown from a window and trampled in this town, as prophesied", ["2 Kings 9:30-37"]),
        "naboth": ("the man of this town killed for refusing to sell King Ahab his vineyard", ["1 Kings 21:1-13"]),
    },
    "mahanaim": {
        "abner": ("set up Ish-bosheth as king here after Saul's death", ["2 Samuel 2:8-9"]),
        "ahimaaz-2": ("ran from here to bring David the news of the battle with Absalom", ["2 Samuel 18:19-23"]),
        "baanah": ("one of Ish-bosheth's captains, based here, who murdered his own king", ["2 Samuel 4:5-7"]),
        "ish-bosheth": ("Saul's son, made rival king over Israel from this town", ["2 Samuel 2:8-10"]),
        "machir-2": ("of Lo-debar, who brought David supplies here during Absalom's revolt", ["2 Samuel 17:27-29"]),
        "rechab": ("one of Ish-bosheth's captains, based here, who murdered his own king", ["2 Samuel 4:5-7"]),
    },
    "mount-sinai": {
        "bezalel": ("filled with God's Spirit here to design and build the tabernacle", ["Exodus 31:2-5"]),
        "elijah": ("fled to this mountain and heard God in a low whisper", ["1 Kings 19:8-12"]),
        "elzaphan": ("carried the bodies of Nadab and Abihu out of the camp here", ["Leviticus 10:4"]),
        "hobab": ("asked by Moses to guide Israel onward from this mountain", ["Numbers 10:29-31"]),
        "hur": ("held up Moses's hands, and was left in charge while Moses climbed the mountain", ["Exodus 17:12", "Exodus 24:14"]),
        "oholiab": ("appointed with Bezalel to build the tabernacle here", ["Exodus 31:6"]),
    },
    "tirzah": {
        "abijah-2": ("Jeroboam's son, whose death at this capital the prophet Ahijah foretold", ["1 Kings 14:12", "1 Kings 14:17"]),
        "baasha": ("reigned over Israel from this city for twenty-four years", ["1 Kings 15:33"]),
        "elah-2": ("Baasha's son, killed while drunk at this city by Zimri", ["1 Kings 16:8-10"]),
        "menahem": ("marched up from this city to seize Israel's throne", ["2 Kings 15:14"]),
        "omri": ("besieged this city until Zimri burned the palace, then built Samaria as his capital", ["1 Kings 16:17-24"]),
        "zimri-2": ("burned the palace of this city over himself after seven days as king", ["1 Kings 16:15-18"]),
    },
    "antioch": {
        "agabus": ("prophesied here of a famine, prompting the church to send relief to Judea", ["Acts 11:27-30"]),
        "barnabas": ("sent to this church, where he fetched Saul and disciples were first called Christians", ["Acts 11:22-26"]),
        "judas-5": ("carried the Jerusalem council's letter to this church and encouraged it", ["Acts 15:22", "Acts 15:32"]),
        "manaen": ("one of the prophets and teachers of this church", ["Acts 13:1"]),
        "nicolas": ("a convert of this city, chosen among the seven at Jerusalem", ["Acts 6:5"]),
        "peter": ("ate with Gentiles here until he drew back, and Paul opposed him to his face", ["Galatians 2:11-14"]),
        "silas": ("carried the Jerusalem council's letter to this church with Judas", ["Acts 15:22"]),
    },
    "gibeon": {
        "abner": ("fought David's men by the pool here and killed Asahel in the retreat", ["2 Samuel 2:12-23"]),
        "adoni-zedek": ("king of Jerusalem, who led the coalition that attacked this city for allying with Israel", ["Joshua 10:1-5"]),
        "amasa": ("struck down by Joab at the great stone in this town", ["2 Samuel 20:8-10"]),
        "armoni": ("a son of Saul, hanged before the LORD at this town", ["2 Samuel 21:8-9"]),
        "asahel": ("killed by Abner while chasing him from the battle here", ["2 Samuel 2:18-23"]),
        "piram": ("king of Jarmuth, in the coalition against this city", ["Joshua 10:3-5"]),
        "solomon": ("sacrificed at the great high place here, where God gave him wisdom in a dream", ["1 Kings 3:4-12"]),
    },
    "midian": {
        "gershom": ("Moses's elder son, born during his father's exile in this land", ["Exodus 2:22"]),
        "hur-2": ("one of the five kings of this land killed by Israel", ["Numbers 31:8"]),
        "jethro": ("priest of this land and Moses's father-in-law", ["Exodus 3:1", "Exodus 18:1"]),
        "moses": ("fled here from Egypt and kept Jethro's flock for forty years", ["Exodus 2:15-21"]),
        "zalmunna": ("a king of this people, captured and killed by Gideon", ["Judges 8:21"]),
        "zebah": ("a king of this people, captured and killed by Gideon", ["Judges 8:21"]),
        "zipporah": ("the priest of Midian's daughter, who became Moses's wife", ["Exodus 2:21"]),
    },
    "mizpah": {
        "azariah-16": ("accused Jeremiah of lying and helped lead the remnant to Egypt from here", ["Jeremiah 43:2-7"]),
        "baalis": ("the Ammonite king who sent Ishmael to kill Gedaliah at this town", ["Jeremiah 40:14"]),
        "gedaliah": ("Babylon's appointed governor, based and assassinated at this town", ["Jeremiah 40:6-7", "Jeremiah 41:1-3"]),
        "ishmael-2": ("assassinated Gedaliah and many others at this town", ["Jeremiah 41:1-3"]),
        "jezaniah": ("a captain who submitted to Gedaliah and sought Jeremiah's counsel here", ["Jeremiah 40:8", "Jeremiah 42:1"]),
        "johanan": ("warned Gedaliah of the plot here, then avenged his murder", ["Jeremiah 40:13-16", "Jeremiah 41:11-14"]),
        "samuel": ("gathered Israel here to repent, and Israel routed the Philistines", ["1 Samuel 7:5-11"]),
    },
    "wilderness-of-paran": {
        "abiram": ("a Reubenite swallowed by the earth for rebelling against Moses in this wilderness", ["Numbers 16:27-33"]),
        "gaddi": ("the spy from Manasseh sent from this wilderness into Canaan", ["Numbers 13:3", "Numbers 13:11"]),
        "gaddiel": ("the spy from Zebulun sent from this wilderness into Canaan", ["Numbers 13:3", "Numbers 13:10"]),
        "geuel": ("the spy from Gad sent from this wilderness into Canaan", ["Numbers 13:3", "Numbers 13:15"]),
        "hagar": ("wandered in this wilderness with Ishmael, where God showed her a well", ["Genesis 21:14-19"]),
        "igal": ("the spy from Issachar sent from this wilderness into Canaan", ["Numbers 13:3", "Numbers 13:7"]),
        "ishmael": ("grew up in this wilderness and became an archer there", ["Genesis 21:20-21"]),
    },

    # ---- eight- and nine-person places ----
    "gilead": {
        "chimham": ("Barzillai's son from this region, taken into David's care", ["2 Samuel 19:37-40"]),
        "elijah": ("a Tishbite of this region, who announced the drought to Ahab", ["1 Kings 17:1"]),
        "gilead-2": ("father of the judge Jephthah, of this region", ["Judges 11:1"]),
        "jair": ("captured towns in this region and named them after himself", ["Numbers 32:41"]),
        "jair-2": ("a judge of this region, whose thirty sons ruled thirty of its towns", ["Judges 10:3-4"]),
        "jephthah": ("the outcast of this region, called back to lead it against Ammon", ["Judges 11:4-11"]),
        "machir": ("of Manasseh, whose descendants conquered and settled this region", ["Numbers 32:39-40"]),
        "nobah": ("of Manasseh, who took Kenath in this region and renamed it for himself", ["Numbers 32:42"]),
    },
    "jericho": {
        "abiram-2": ("Hiel's firstborn, who died when his father refounded this city", ["1 Kings 16:34"]),
        "achan": ("took plunder devoted to destruction from this city, bringing defeat on Israel", ["Joshua 7:1"]),
        "amasa-2": ("an Ephraimite leader who saw Judah's captives clothed and returned to this city", ["2 Chronicles 28:15"]),
        "bartimaeus": ("the blind beggar of this city, healed as Jesus was leaving it", ["Mark 10:46-52"]),
        "eglon": ("the Moabite king who seized “the city of palms” and its region", ["Judges 3:13"]),
        "hiel": ("rebuilt this city under Ahab, losing two sons as Joshua had cursed", ["1 Kings 16:34"]),
        "rahab": ("the prostitute of this city who hid the spies and was spared when it fell", ["Joshua 2:1", "Joshua 6:22-25"]),
        "segub": ("Hiel's youngest son, who died when his father set up this city's gates", ["1 Kings 16:34"]),
        "zaccheus": ("the chief tax collector of this city who climbed a tree to see Jesus", ["Luke 19:1-8"]),
    },
    "plains-of-moab": {
        "balaam": ("hired by Balak here to curse Israel, but able only to bless", ["Numbers 22:1", "Numbers 23:11-12"]),
        "cozbi": ("the Midianite woman struck down with Zimri during Israel's sin here", ["Numbers 25:1-8"]),
        "hoglah": ("a daughter of Zelophehad who sought her father's inheritance here", ["Numbers 27:1-7"]),
        "hur-2": ("a Midianite king killed in the war of vengeance fought from here", ["Numbers 31:8"]),
        "mahlah": ("a daughter of Zelophehad who sought her father's inheritance here", ["Numbers 27:1-7"]),
        "milcah-2": ("a daughter of Zelophehad who sought her father's inheritance here", ["Numbers 27:1-7"]),
        "moses": ("gave the addresses of Deuteronomy here and viewed the promised land", ["Deuteronomy 1:5", "Deuteronomy 34:1"]),
        "noah-2": ("a daughter of Zelophehad who sought her father's inheritance here", ["Numbers 27:1-7"]),
        "tirzah": ("a daughter of Zelophehad who sought her father's inheritance here", ["Numbers 27:1-7"]),
    },
    "shiloh": {
        "abijah-2": ("Jeroboam's sick son, over whom Ahijah of this town prophesied", ["1 Kings 14:1-4"]),
        "ahijah": ("the prophet of this town who foretold the tearing away of the ten tribes", ["1 Kings 11:29-31"]),
        "eli": ("high priest and judge at the sanctuary here", ["1 Samuel 1:9", "1 Samuel 4:18"]),
        "elkanah-2": ("came here yearly to worship and sacrifice to the LORD", ["1 Samuel 1:3"]),
        "hannah": ("prayed here for a son and later left the young Samuel with Eli", ["1 Samuel 1:9-11", "1 Samuel 1:24-28"]),
        "hophni": ("a corrupt priest son of Eli, who abused the offerings here", ["1 Samuel 2:12-17"]),
        "ichabod": ("born here as the news came that the ark had been captured", ["1 Samuel 4:19-22"]),
        "phinehas-2": ("a corrupt priest son of Eli, killed the day the ark was taken", ["1 Samuel 4:11", "1 Samuel 4:17"]),
        "samuel": ("grew up ministering before the LORD here and first heard God's voice", ["1 Samuel 3:1-10"]),
    },

    # ---- ten- to twenty-one-person places ----
    "bethel": {
        "abiram-2": ("son of Hiel of this town, lost when his father rebuilt Jericho", ["1 Kings 16:34"]),
        "amaziah-3": ("priest of the royal sanctuary here, who tried to silence Amos", ["Amos 7:10-13"]),
        "amos": ("confronted here by the priest and ordered to prophesy elsewhere", ["Amos 7:12-15"]),
        "deborah": ("Rebekah's nurse, buried under an oak below this town", ["Genesis 35:8"]),
        "hiel": ("of this town, who rebuilt Jericho and lost two sons", ["1 Kings 16:34"]),
        "israel": ("dreamed of the stairway to heaven here and named the place", ["Genesis 28:11-19"]),
        "jeroboam": ("set up one of his two golden calves in this town", ["1 Kings 12:28-29"]),
        "regemmelech": ("sent from this town to ask the priests whether to keep the fasts", ["Zechariah 7:2-3"]),
        "samuel": ("judged Israel on the yearly circuit through this town", ["1 Samuel 7:16"]),
        "sharezer-2": ("sent from this town to inquire in Jerusalem about the fasts", ["Zechariah 7:2"]),
    },
    "damascus": {
        "ananias-2": ("the disciple of this city who restored Saul's sight", ["Acts 9:10-18"]),
        "aretas": ("the king whose governor here guarded the gates to seize Paul", ["2 Corinthians 11:32"]),
        "ben-hadad": ("a king of this city, who besieged Samaria", ["1 Kings 20:1"]),
        "ben-hadad-2": ("a king of this city, Hazael's son", ["2 Kings 13:24"]),
        "eliezer": ("Abram's steward, “of Damascus,” his heir before Isaac was born", ["Genesis 15:2"]),
        "hazael": ("seized this city's throne by smothering Ben-hadad", ["2 Kings 8:15"]),
        "paul": ("blinded on the road to this city and baptized here", ["Acts 9:3-19"]),
        "rezin": ("its king, killed when Assyria captured the city", ["2 Kings 16:9"]),
        "rezon": ("seized this city and reigned there as an adversary to Solomon", ["1 Kings 11:23-25"]),
        "tiglath-pileser": ("captured this city and deported its people for King Ahaz", ["2 Kings 16:9"]),
    },
    "moab": {
        "balak": ("its king, who hired Balaam to curse Israel", ["Numbers 22:2-6"]),
        "chilion": ("Elimelech's son, who married and died in this land", ["Ruth 1:2-5"]),
        "eglon": ("its king, who oppressed Israel for eighteen years", ["Judges 3:12-14"]),
        "ehud": ("killed King Eglon and subdued this nation", ["Judges 3:21-30"]),
        "elimelech": ("left Bethlehem for this land in a famine and died there", ["Ruth 1:1-3"]),
        "joram-2": ("Israel's king, who marched against this land with Judah and Edom", ["2 Kings 3:6-7"]),
        "mahlon": ("Elimelech's son, who married Ruth in this land and died there", ["Ruth 1:4-5"]),
        "mesha": ("its king, who rebelled against Israel and sacrificed his own son", ["2 Kings 3:4-5", "2 Kings 3:27"]),
        "naomi": ("left this land for Bethlehem after losing her husband and both sons here", ["Ruth 1:6-7"]),
        "orpah": ("Naomi's daughter-in-law, who turned back to this, her own land", ["Ruth 1:14"]),
        "ruth": ("a widow of this land who left it to follow Naomi and Naomi's God", ["Ruth 1:16-19"]),
    },
    "shechem": {
        "abimelech-2": ("made himself king here after murdering his brothers, then destroyed the city", ["Judges 9:1-6", "Judges 9:45"]),
        "adoram": ("Rehoboam's labor officer, stoned to death by Israel at this town", ["1 Kings 12:18"]),
        "dinah": ("Jacob's daughter, violated by the prince of this city", ["Genesis 34:1-2"]),
        "gaal": ("stirred this city's leaders to revolt against Abimelech", ["Judges 9:26-29"]),
        "hamor": ("the Hivite ruler of this city who negotiated with Jacob's sons", ["Genesis 34:6-24"]),
        "jeroboam": ("rebuilt this town and first reigned from it", ["1 Kings 12:25"]),
        "jotham": ("shouted his parable over this city from Mount Gerizim", ["Judges 9:7"]),
        "levi": ("with Simeon, massacred the men of this city after Dinah's violation", ["Genesis 34:25-26"]),
        "rehoboam": ("came here to be made king, and lost the ten northern tribes", ["1 Kings 12:1-16"]),
        "shechem": ("the prince of this city who violated Dinah", ["Genesis 34:2"]),
        "simeon": ("with Levi, massacred the men of this city after Dinah's violation", ["Genesis 34:25-26"]),
    },
    "corinth": {
        "achaicus": ("of this church, who visited Paul and refreshed his spirit", ["1 Corinthians 16:17-18"]),
        "apollos": ("watered here what Paul had planted, and some formed a faction for him", ["1 Corinthians 3:6", "1 Corinthians 1:12"]),
        "aquila": ("made tents here with Paul and hosted the church", ["Acts 18:2-3"]),
        "crispus": ("the synagogue ruler here who believed with all his household", ["Acts 18:8"]),
        "erastus-2": ("the city treasurer here, one of Paul's helpers", ["Romans 16:23"]),
        "forunatus": ("of this church, who visited Paul and refreshed his spirit", ["1 Corinthians 16:17-18"]),
        "gaius": ("Paul's host here, and host to the whole church", ["Romans 16:23", "1 Corinthians 1:14"]),
        "gallio": ("the proconsul who dismissed the Jews' charges against Paul here", ["Acts 18:12-16"]),
        "priscilla": ("made tents here with Paul and hosted the church", ["Acts 18:2-3"]),
        "silas": ("joined Paul here from Macedonia as he preached", ["Acts 18:5"]),
        "sosthenes": ("the synagogue ruler beaten before Gallio's judgment seat here", ["Acts 18:17"]),
        "tertius": ("wrote down Paul's letter to the Romans while at this city", ["Romans 16:22-23"]),
        "titus": ("sent to this church over the painful letter, and returned with good news", ["2 Corinthians 7:6-7", "2 Corinthians 7:13"]),
    },
    "caesarea": {
        "agabus": ("warned Paul here that he would be bound in Jerusalem", ["Acts 21:10-11"]),
        "agrippa": ("the king who heard Paul's defense here", ["Acts 25:23", "Acts 26:1"]),
        "ananias-3": ("the high priest who came here to accuse Paul before Felix", ["Acts 24:1"]),
        "bernice": ("attended Paul's hearing here with her brother King Agrippa", ["Acts 25:23"]),
        "blastus": ("Herod Agrippa I's chamberlain, at this city where Herod was struck down", ["Acts 12:20-23"]),
        "caesar-2": ("the emperor to whom Paul appealed from this city", ["Acts 25:11-12"]),
        "cornelius": ("the centurion of this city, first Gentile convert, baptized by Peter", ["Acts 10:1", "Acts 10:44-48"]),
        "drusilla": ("Felix's wife, who heard Paul speak of faith in Christ here", ["Acts 24:24"]),
        "felix": ("the governor who held Paul prisoner here for two years", ["Acts 24:27"]),
        "festus": ("the governor who heard Paul here and sent him to Rome", ["Acts 25:1-12"]),
        "herod-3": ("struck down at this city after accepting the crowd's worship", ["Acts 12:19-23"]),
        "julius": ("the centurion who took charge of Paul here for the voyage to Rome", ["Acts 27:1"]),
        "lysias": ("the tribune who sent Paul here under armed guard from Jerusalem", ["Acts 23:23-33"]),
        "philip-3": ("the evangelist whose home here hosted Paul and his companions", ["Acts 21:8-9"]),
    },
    "susa": {
        "ahasuerus": ("the Persian king who reigned from this citadel and made Esther queen", ["Esther 1:2", "Esther 2:16-17"]),
        "artaxerxes": ("the Persian king from whose court here Nehemiah was sent to Judah", ["Nehemiah 1:1", "Nehemiah 2:1"]),
        "bigthan": ("a royal guard here who plotted to assassinate the king", ["Esther 2:21"]),
        "daniel-2": ("saw the vision of the ram and the goat while at this citadel", ["Daniel 8:2"]),
        "esther": ("the Jewish queen who risked her life before the king in this citadel", ["Esther 4:16", "Esther 5:1-2"]),
        "haman": ("the king's chief official here, hanged on the gallows he built for Mordecai", ["Esther 3:1", "Esther 7:9-10"]),
        "hanani-4": ("brought Nehemiah the news here of Jerusalem's broken walls", ["Nehemiah 1:2-3"]),
        "harbona": ("the king's eunuch here, who pointed out Haman's gallows", ["Esther 7:9"]),
        "hathach": ("the eunuch here who carried messages between Esther and Mordecai", ["Esther 4:5-10"]),
        "hegai": ("the eunuch in charge of the harem here, who favored Esther", ["Esther 2:8-9"]),
        "memucan": ("the prince here who advised deposing Queen Vashti", ["Esther 1:16-21"]),
        "mordecai-2": ("the Jew at the king's gate here, raised to second in the kingdom", ["Esther 2:19-21", "Esther 10:3"]),
        "nehemiah": ("cupbearer to the king in this citadel before returning to rebuild Judah", ["Nehemiah 1:11", "Nehemiah 2:1"]),
        "vashti": ("the queen here, deposed for refusing the king's summons", ["Esther 1:9-19"]),
    },
    "galilee": {
        "andrew": ("a fisherman of this region, among the first Jesus called", ["Matthew 4:18-20"]),
        "herod-2": ("tetrarch of this region, who imprisoned and beheaded John the Baptist", ["Luke 3:1", "Mark 6:14-27"]),
        "herodias": ("married to the tetrarch of this region, whose rebuke by John she resented", ["Mark 6:17-19"]),
        "james": ("a fisherman of this region, called by Jesus with his brother John", ["Matthew 4:21-22"]),
        "joanna": ("a woman of Herod's household here, who supported Jesus's ministry from her means", ["Luke 8:3"]),
        "john-2": ("a fisherman of this region, called by Jesus with his brother James", ["Matthew 4:21-22"]),
        "judas-of-galilee": ("the rebel of this region recalled by Gamaliel before the council", ["Acts 5:37"]),
        "matthew": ("a tax collector of this region, called by Jesus to follow", ["Mark 2:14"]),
        "nathanael": ("of Cana in this region, called to Jesus through his friend Philip", ["John 1:45-49", "John 21:2"]),
        "peter": ("a fisherman of this region, leader among the Twelve", ["Matthew 4:18"]),
        "philip": ("of Bethsaida in this region, one of the Twelve", ["John 1:43-44"]),
        "salome": ("a woman who followed and provided for Jesus in this region", ["Mark 15:40-41"]),
        "salome-2": ("Herodias's daughter, whose dance in this region cost John the Baptist his head", ["Mark 6:22-28"]),
        "thomas": ("one of the Twelve, called during Jesus's ministry in this region", ["John 21:2"]),
    },
    "hebron": {
        "abigail": ("became David's wife and came with him when he was made king here", ["1 Samuel 25:42", "2 Samuel 2:1-3"]),
        "abner": ("defected to David here, and was murdered by Joab at the city gate", ["2 Samuel 3:20-27"]),
        "ahiman": ("one of the giant sons of Anak dwelling in this city", ["Numbers 13:22"]),
        "ahinoam-2": ("a wife of David, who came with him when he was crowned here", ["2 Samuel 2:2-3"]),
        "aner": ("an Amorite ally of Abram near this city", ["Genesis 14:13", "Genesis 14:24"]),
        "caleb": ("given this city as his inheritance, and drove out its giants at eighty-five", ["Joshua 14:12-14"]),
        "david": ("anointed king of Judah here and reigned seven years before taking Jerusalem", ["2 Samuel 2:4", "2 Samuel 2:11"]),
        "ephron": ("the Hittite of this city who sold Abraham the cave of Machpelah", ["Genesis 23:8-18"]),
        "eshcol": ("an Amorite ally of Abram near this city", ["Genesis 14:13", "Genesis 14:24"]),
        "hoham": ("king of this city, executed by Joshua at Makkedah", ["Joshua 10:3", "Joshua 10:23-26"]),
        "mamre": ("the Amorite by whose oaks near this city Abram lived", ["Genesis 13:18", "Genesis 14:13"]),
        "othniel": ("Caleb's nephew, who took nearby Kiriath-sepher to win Achsah in marriage", ["Joshua 15:16-17"]),
        "rebekah": ("buried in the cave of Machpelah near this city", ["Genesis 49:31"]),
        "sheshai": ("one of the giant sons of Anak dwelling in this city", ["Numbers 13:22"]),
    },
    "paddan-aram": {
        "asher": ("born here to Jacob and Leah's servant Zilpah", ["Genesis 30:12-13"]),
        "bethuel": ("the Aramean of this region, father of Rebekah and Laban", ["Genesis 25:20"]),
        "bilhah": ("Rachel's servant here, who bore Dan and Naphtali to Jacob", ["Genesis 30:3-8"]),
        "dan": ("born here to Jacob and Bilhah", ["Genesis 30:5-6"]),
        "gad": ("born here to Jacob and Zilpah", ["Genesis 30:10-11"]),
        "israel": ("served Laban here twenty years and gained his wives, children, and flocks", ["Genesis 28:2", "Genesis 31:38"]),
        "issachar": ("born here to Jacob and Leah", ["Genesis 30:17-18"]),
        "laban": ("Jacob's uncle here, who tricked him into marrying Leah first", ["Genesis 29:15-27"]),
        "leah": ("Laban's elder daughter here, given to Jacob by her father's trick", ["Genesis 29:23-25"]),
        "naphtali": ("born here to Jacob and Bilhah", ["Genesis 30:7-8"]),
        "rachel": ("Laban's younger daughter here, for whom Jacob served fourteen years", ["Genesis 29:18-28"]),
        "rebekah": ("sought from this region as a wife for Isaac", ["Genesis 25:20"]),
        "reuben": ("Jacob's firstborn, born here to Leah", ["Genesis 29:31-32"]),
        "zebulun": ("born here to Jacob and Leah", ["Genesis 30:19-20"]),
        "zilpah": ("Leah's servant here, who bore Gad and Asher to Jacob", ["Genesis 30:9-13"]),
    },
    "sinai": {
        "aaron": ("consecrated Israel's first high priest here, and made the golden calf", ["Exodus 28:1", "Exodus 32:2-4"]),
        "abihu": ("an ordained priest here, struck down for offering unauthorized fire", ["Leviticus 10:1-2"]),
        "hoglah": ("a daughter of Zelophehad, numbered among Israel here", ["Numbers 26:33"]),
        "ithamar": ("Aaron's youngest son, ordained priest here, who oversaw the Levites' work", ["Exodus 38:21"]),
        "jethro": ("came to Moses here and advised appointing capable men as judges over Israel", ["Exodus 18:5", "Exodus 18:13-24"]),
        "joshua": ("Moses's aide, who guarded the tent of meeting here and went partway up the mountain", ["Exodus 24:13", "Exodus 33:11"]),
        "korah-3": ("a Levite who led a rebellion against Moses and Aaron here and was swallowed by the earth", ["Numbers 16:1-33"]),
        "mahlah": ("a daughter of Zelophehad, numbered among Israel here", ["Numbers 26:33"]),
        "milcah-2": ("a daughter of Zelophehad, numbered among Israel here", ["Numbers 26:33"]),
        "moses": ("received the Law and the covenant from God here", ["Exodus 19:20", "Exodus 24:12"]),
        "nadab": ("an ordained priest here, struck down for offering unauthorized fire", ["Leviticus 10:1-2"]),
        "noah-2": ("a daughter of Zelophehad, numbered among Israel here", ["Numbers 26:33"]),
        "shelumiel": ("leader of the tribe of Simeon, who helped Moses number the people here", ["Numbers 1:6"]),
        "tirzah": ("a daughter of Zelophehad, numbered among Israel here", ["Numbers 26:33"]),
        "zipporah": ("Moses's wife, brought to him here by her father Jethro", ["Exodus 18:2-5"]),
    },
    "ephesus": {
        "achaicus": ("of Corinth, who visited Paul during his long stay in this city", ["1 Corinthians 16:8", "1 Corinthians 16:17"]),
        "alexander-3": ("the Jew pushed forward by the crowd during the silversmiths' riot here", ["Acts 19:33"]),
        "alexander-4": ("the coppersmith who did Paul great harm and strongly opposed his message", ["2 Timothy 4:14-15"]),
        "apollos": ("taught boldly in the synagogue here before Priscilla and Aquila corrected him", ["Acts 18:24-26"]),
        "aquila": ("settled here with Paul and instructed Apollos more accurately", ["Acts 18:19", "Acts 18:26"]),
        "aristarchus": ("seized by the mob and dragged into the theater here during the riot", ["Acts 19:29"]),
        "demetrius": ("the silversmith who stirred this city to riot against Paul", ["Acts 19:24-29"]),
        "erastus": ("sent ahead from here to Macedonia while Paul stayed on in Asia", ["Acts 19:22"]),
        "forunatus": ("of Corinth, who visited Paul during his stay in this city", ["1 Corinthians 16:8", "1 Corinthians 16:17"]),
        "hymenaeus": ("handed over to Satan for the ruin of his faith, and later denied here", ["1 Timothy 1:19-20"]),
        "onesiphorus": ("of this city, who often refreshed Paul and searched him out in Rome", ["2 Timothy 1:16-18"]),
        "philetus": ("who taught here that the resurrection had already happened", ["2 Timothy 2:17-18"]),
        "priscilla": ("settled here with Aquila and instructed Apollos more accurately", ["Acts 18:19", "Acts 18:26"]),
        "timothy": ("left here by Paul to correct the false teaching spreading in the church", ["1 Timothy 1:3"]),
        "trophimus": ("of this city, whose presence with Paul in Jerusalem sparked the temple riot", ["Acts 21:29"]),
    },
    "bethlehem": {
        "abinadab-3": ("Jesse's son of this town, passed over when Samuel anointed David", ["1 Samuel 16:8"]),
        "benjamin": ("Jacob's youngest son, born as Rachel died on the road to this town", ["Genesis 35:16-19"]),
        "boaz": ("the landowner of this town who redeemed and married Ruth", ["Ruth 2:1", "Ruth 4:9-13"]),
        "caesar-augustus": ("whose census decree brought Joseph and Mary to this town", ["Luke 2:1-5"]),
        "chilion": ("a son of Elimelech and Naomi of this town", ["Ruth 1:1-2"]),
        "david": ("the shepherd boy of this town, anointed king here by Samuel", ["1 Samuel 16:1", "1 Samuel 16:13"]),
        "elhanan": ("one of David's mighty men, from this town", ["2 Samuel 23:24"]),
        "eliab-3": ("Jesse's eldest son of this town, passed over by Samuel", ["1 Samuel 16:6"]),
        "elimelech": ("left this town for Moab during a famine", ["Ruth 1:1-2"]),
        "herod": ("ordered the killing of this town's baby boys after the magi outwitted him", ["Matthew 2:16"]),
        "ibzan": ("a judge of Israel from this town", ["Judges 12:8-10"]),
        "jesse": ("the Bethlehemite whose youngest son David was anointed king here", ["1 Samuel 16:1"]),
        "joseph-6": ("of David's line, who came to this town for the census with Mary", ["Luke 2:4"]),
        "mahlon": ("a son of Elimelech and Naomi of this town, who married Ruth", ["Ruth 1:1-5"]),
        "mary": ("who gave birth to Jesus in this town", ["Luke 2:4-7"]),
        "naomi": ("returned to this town from Moab, widowed and empty", ["Ruth 1:19-21"]),
        "obed": ("son of Boaz and Ruth, born in this town, grandfather of King David", ["Ruth 4:17"]),
        "rachel": ("died near this town giving birth to Benjamin, and was buried there", ["Genesis 35:19"]),
        "ruth": ("gleaned in the fields of this town and married Boaz here", ["Ruth 2:2-3", "Ruth 4:13"]),
        "shimeah": ("one of Jesse's sons of this town, an elder brother of David", ["1 Samuel 16:9"]),
    },
    "rome": {
        "andronicus": ("a kinsman of Paul, imprisoned with him, greeted in the letter to this city", ["Romans 16:7"]),
        "aquila": ("hosted a church in this city, greeted by Paul in Romans", ["Romans 16:3-5"]),
        "aristarchus": ("accompanied Paul on the voyage that brought him a prisoner to this city", ["Acts 27:2"]),
        "caesar": ("the emperor whose image was on the tribute coin in Jesus's teaching", ["Mark 12:16-17"]),
        "caesar-2": ("the emperor to whom Paul appealed, carrying his case to this city", ["Acts 28:19"]),
        "caesar-augustus": ("this empire's first emperor, whose census decree reached Judea", ["Luke 2:1"]),
        "claudius": ("emperor here, whose edict expelling Jews sent Aquila and Priscilla away", ["Acts 18:2"]),
        "demas": ("a fellow worker who deserted Paul here, having loved this present world", ["2 Timothy 4:10"]),
        "epanetus": ("greeted by Paul in this city as the first convert to Christ from Asia", ["Romans 16:5"]),
        "epaphras": ("of Colossae, Paul's fellow prisoner in this city", ["Philemon 1:23", "Colossians 4:12"]),
        "epaphroditus": ("sent by Philippi with a gift to Paul in this city, where he fell ill", ["Philippians 2:25-27"]),
        "junias": ("a kinsman of Paul, imprisoned with him, greeted in the letter to this city", ["Romans 16:7"]),
        "mark": ("with Paul during his imprisonment in this city", ["Colossians 4:10", "2 Timothy 4:11"]),
        "mary-5": ("a hard worker in this church, greeted by name by Paul", ["Romans 16:6"]),
        "onesimus": ("the runaway slave converted by Paul during his imprisonment in this city", ["Philemon 1:10"]),
        "onesiphorus": ("searched hard for Paul in this city until he found him", ["2 Timothy 1:17"]),
        "paul": ("brought here as a prisoner, and preached the kingdom under guard", ["Acts 28:16", "Acts 28:30-31"]),
        "persis": ("a woman of this church who worked hard in the Lord", ["Romans 16:12"]),
        "priscilla": ("hosted a church in this city with her husband Aquila", ["Romans 16:3-5"]),
        "rufus": ("greeted in this church as choice in the Lord", ["Romans 16:13"]),
        "tychicus": ("a courier of the letters Paul wrote from his imprisonment here", ["Colossians 4:7-8"]),
    },

    # ---- capped places: most significant figures only ----
    "babylon": {
        "abed-nego": ("one of the three preserved unharmed in the fiery furnace in this city", ["Daniel 3:19-27"]),
        "meshach": ("one of the three preserved unharmed in the fiery furnace in this city", ["Daniel 3:19-27"]),
        "shadrach": ("one of the three preserved unharmed in the fiery furnace in this city", ["Daniel 3:19-27"]),
        "daniel-2": ("an exile here who rose to high office and was saved from the lions' den", ["Daniel 2:48", "Daniel 6:16-23"]),
        "nebuchadnezzar": ("its king, who deported Judah here and was himself humbled by God", ["Daniel 1:1", "Daniel 4:28-33"]),
        "belshazzar": ("its last king, who saw the writing on the wall the night the city fell", ["Daniel 5:1", "Daniel 5:30"]),
        "evil-merodach": ("its king, who freed the exiled Jehoiachin from prison here", ["2 Kings 25:27-30"]),
        "cyrus": ("conqueror of this city, who freed the exiles to return home", ["Ezra 1:1-2"]),
        "ezekiel": ("prophesied among the exiles by the Chebar canal near this city", ["Ezekiel 1:1-3"]),
        "jehoiachin": ("Judah's exiled king, held prisoner in this city for thirty-seven years", ["2 Kings 24:15", "2 Kings 25:27"]),
        "zedekiah-2": ("Judah's last king, brought here blinded and in chains", ["2 Kings 25:7"]),
        "zerubbabel": ("of the royal line, who led the first exiles back from this city", ["Ezra 2:2"]),
        "ezra": ("the scribe who came up from this city to teach the Law in Jerusalem", ["Ezra 7:6"]),
        "nebuzaradan": ("the guard commander who burned Jerusalem and deported its people here", ["2 Kings 25:8-11"]),
    },
    "canaan": {
        "abraham": ("called to this land and given it by covenant for his offspring", ["Genesis 12:5-7"]),
        "isaac": ("born and lived his whole life in this land", ["Genesis 26:1-6"]),
        "joseph": ("sold by his brothers out of this land into slavery in Egypt", ["Genesis 37:12-28"]),
        "joshua": ("led Israel across the Jordan to conquer and divide this land", ["Joshua 1:2-6", "Joshua 11:23"]),
        "lot": ("came to this land with Abram, then chose the Jordan plain", ["Genesis 13:11-12"]),
        "sarah": ("came to this land with Abraham and was buried at Machpelah", ["Genesis 23:2", "Genesis 23:19"]),
        "hagar": ("Sarah's servant, given to Abram in this land to bear a son", ["Genesis 16:3"]),
        "ishmael": ("Abram's son by Hagar, born in this land", ["Genesis 16:15-16"]),
        "esau": ("Isaac's elder son, who moved out of this land to settle in Seir", ["Genesis 36:6-8"]),
        "judah": ("Jacob's fourth son, who married and raised sons in this land", ["Genesis 38:1-5"]),
        "perez": ("son of Judah, born in this land, an ancestor of David", ["Genesis 38:29"]),
    },
    "egypt": {
        "joseph": ("sold here as a slave, then raised to govern the land and save it from famine", ["Genesis 41:39-43"]),
        "israel": ("came down here with his household and died here after seeing Joseph again", ["Genesis 46:5-7", "Genesis 49:33"]),
        "moses": ("born here under Pharaoh's death decree, and later led Israel out", ["Exodus 2:1-10", "Exodus 12:31"]),
        "aaron": ("sent back here to be Moses's spokesman before Pharaoh", ["Exodus 4:27-31"]),
        "miriam": ("watched over the infant Moses here, and led Israel's song after the sea", ["Exodus 2:4-8", "Exodus 15:20"]),
        "jochebed": ("hid her son Moses here for three months, then set him afloat on the Nile", ["Exodus 2:1-3"]),
        "pharaoh": ("a king of this land whose hardened heart brought on the ten plagues", ["Exodus 7:13", "Exodus 12:29"]),
        "abraham": ("went down to this land in a famine and passed Sarah off as his sister", ["Genesis 12:10-13"]),
        "hagar": ("an Egyptian, Sarah's servant and the mother of Ishmael", ["Genesis 16:1"]),
        "potiphar": ("the officer of this land who bought Joseph and then had him jailed", ["Genesis 39:1", "Genesis 39:20"]),
        "asenath": ("the Egyptian priest's daughter given to Joseph as his wife here", ["Genesis 41:45"]),
        "shiphrah": ("a midwife here who feared God and spared the Hebrew baby boys", ["Exodus 1:15-17"]),
        "puah": ("a midwife here who feared God and spared the Hebrew baby boys", ["Exodus 1:15-17"]),
        "shishak": ("its king, who plundered the temple in Jerusalem in Rehoboam's reign", ["1 Kings 14:25-26"]),
        "pharaoh-neco": ("its king, who killed Josiah and made Judah a tribute-paying vassal", ["2 Kings 23:29", "2 Kings 23:34"]),
        "jeremiah-6": ("carried down into this land by the fleeing remnant against his word", ["Jeremiah 43:6-7"]),
        "jehoahaz-2": ("Judah's king, deposed by Neco and taken to die in this land", ["2 Kings 23:33-34"]),
    },
    "kingdom-of-israel": {
        "jeroboam": ("its first king, who set up the golden calves at Bethel and Dan", ["1 Kings 12:20", "1 Kings 12:28"]),
        "ahab": ("its king, who married Jezebel and made Baal worship official", ["1 Kings 16:29-33"]),
        "jehu-2": ("anointed its king to destroy the house of Ahab", ["2 Kings 9:1-13"]),
        "elijah": ("its prophet in the days of Ahab and Ahaziah", ["1 Kings 17:1"]),
        "elisha": ("its prophet after Elijah, through the reigns of several kings", ["2 Kings 2:15", "2 Kings 3:11"]),
        "jeroboam-2": ("its king, who restored its borders as the prophet Jonah had foretold", ["2 Kings 14:23-27"]),
        "hoshea": ("its last king, in whose reign Assyria ended the kingdom", ["2 Kings 17:1-6"]),
        "amos": ("a shepherd sent from Judah to prophesy against this kingdom", ["Amos 7:14-15"]),
        "hosea": ("prophesied to this kingdom of its coming judgment and of God's love", ["Hosea 1:1-2"]),
        "baasha": ("its king, who wiped out the house of Jeroboam", ["1 Kings 15:27-29"]),
        "jehoahaz": ("its king, oppressed by Aram until God sent a deliverer", ["2 Kings 13:1-5"]),
        "joram-2": ("its king, killed by Jehu at Jezreel", ["2 Kings 9:24"]),
        "saul": ("Israel's first king, over the tribes before the kingdom divided", ["1 Samuel 15:26"]),
        "david": ("reigned over all Israel from Hebron and then Jerusalem", ["2 Samuel 5:3-5"]),
    },
    "kingdom-of-judah": {
        "rehoboam": ("its first king, in whose reign the kingdom split from Israel", ["1 Kings 12:17-19"]),
        "asa": ("its king, who removed idols and trusted the LORD against a vast army", ["2 Chronicles 14:2-12"]),
        "jehoshaphat-3": ("its king, who sought the LORD and sent teachers of the Law through its towns", ["2 Chronicles 17:3-9"]),
        "ahaz": ("its king, who shut the temple and sacrificed to other gods", ["2 Chronicles 28:24-25"]),
        "hezekiah": ("its king, who cleansed the temple and was spared when Assyria besieged Jerusalem", ["2 Chronicles 29:3", "2 Kings 19:35"]),
        "manasseh-3": ("its most idolatrous king, who repented in Babylonian captivity", ["2 Chronicles 33:1-13"]),
        "josiah": ("its king, who found the Book of the Law and renewed the covenant", ["2 Kings 22:8-13", "2 Kings 23:1-3"]),
        "zedekiah-2": ("its last king, in whose reign Jerusalem fell to Babylon", ["2 Kings 25:1-7"]),
        "jehoram": ("its king, who murdered his own brothers and followed the house of Ahab", ["2 Chronicles 21:4-6"]),
        "jotham-2": ("its king, who did right but did not remove the high places", ["2 Kings 15:32-35"]),
        "isaiah": ("prophesied to its kings from Uzziah through Hezekiah", ["Isaiah 1:1"]),
        "jeremiah-6": ("prophesied through its final decades and its fall", ["Jeremiah 1:1-3"]),
        "habakkuk": ("prophesied to this kingdom of the coming Babylonian judgment", ["Habakkuk 1:1-6"]),
        "zephaniah-3": ("prophesied to this kingdom during Josiah's reign", ["Zephaniah 1:1"]),
    },
    "samaria": {
        "omri": ("founded this city as the capital of the northern kingdom", ["1 Kings 16:23-24"]),
        "ahab": ("built a temple of Baal in this city", ["1 Kings 16:32"]),
        "jezebel": ("queen in this city, who promoted Baal and killed the LORD's prophets", ["1 Kings 18:4"]),
        "elisha": ("lived in this city and guided its kings", ["2 Kings 5:3", "2 Kings 6:32"]),
        "jehu-2": ("wiped out Ahab's family and Baal worship in this city", ["2 Kings 10:11", "2 Kings 10:17-28"]),
        "ben-hadad": ("the Aramean king who besieged this city twice", ["1 Kings 20:1", "2 Kings 6:24"]),
        "gehazi": ("Elisha's servant here, struck with leprosy for his greed", ["2 Kings 5:20-27"]),
        "menahem": ("seized the throne of this city and paid heavy tribute to Assyria", ["2 Kings 15:14-19"]),
        "hoshea": ("its last king, imprisoned when the city fell to Assyria", ["2 Kings 17:1-6"]),
        "shalmaneser": ("the Assyrian king who besieged this city for three years and took it", ["2 Kings 17:5-6"]),
        "shemer": ("the man from whom Omri bought the hill and after whom he named this city", ["1 Kings 16:24"]),
        "philip-3": ("the evangelist who preached Christ in this city with great effect", ["Acts 8:5-8"]),
        "oded": ("the prophet here who turned back Israel's army with its Judean captives", ["2 Chronicles 28:9-11"]),
    },
    "jerusalem": {
        "david": ("captured this city from the Jebusites and made it his capital", ["2 Samuel 5:6-9"]),
        "solomon": ("built the temple and his own palace in this city", ["1 Kings 6:1", "1 Kings 7:1"]),
        "queen-of-sheba": ("came to this city to test Solomon's wisdom with hard questions", ["1 Kings 10:1-7"]),
        "athaliah": ("seized this city's throne, and was put to death at the temple gate", ["2 Kings 11:1-16"]),
        "jehoiada": ("the priest here who overthrew Athaliah and crowned the boy Joash", ["2 Kings 11:4-12"]),
        "hezekiah": ("its king, who trusted God when Assyria's army besieged the city", ["2 Kings 18:13", "2 Kings 19:32-36"]),
        "huldah": ("the prophetess in this city consulted about the newly found Book of the Law", ["2 Kings 22:14-20"]),
        "josiah": ("its king, who purged the city's idols after the Book of the Law was found", ["2 Kings 23:1-14"]),
        "isaiah": ("prophesied in this city through the Assyrian crisis", ["Isaiah 1:1", "Isaiah 37:1-7"]),
        "jeremiah-6": ("prophesied in this city until its fall, and was imprisoned in it", ["Jeremiah 32:2", "Jeremiah 38:6"]),
        "zedekiah-2": ("its last king, captured when Babylon breached the walls", ["2 Kings 25:1-7"]),
        "nebuchadnezzar": ("the Babylonian king whose army destroyed this city and its temple", ["2 Kings 25:8-10"]),
        "zerubbabel": ("led the rebuilding of the temple in this city after the exile", ["Ezra 3:8-10"]),
        "ezra": ("taught the Law to the people gathered in the square of this city", ["Nehemiah 8:1-8"]),
        "nehemiah": ("rebuilt this city's ruined walls in fifty-two days despite opposition", ["Nehemiah 2:11-18", "Nehemiah 6:15"]),
        "absalom": ("seized his father David's throne in this city", ["2 Samuel 15:10-14", "2 Samuel 16:15"]),
        "nicodemus": ("a ruler of the Jews here who came to Jesus by night", ["John 3:1-2"]),
        "annas": ("a former high priest here, before whom Jesus was first brought", ["John 18:13", "John 18:24"]),
        "caiaphas": ("the high priest here who declared Jesus deserving of death", ["Matthew 26:57-66"]),
        "pilate": ("Rome's governor who sentenced Jesus to death in this city", ["John 19:13-16"]),
        "peter": ("preached at Pentecost in this city and led its first church", ["Acts 2:14-41"]),
        "stephen": ("the first martyr, stoned to death outside this city's walls", ["Acts 7:58-60"]),
        "james": ("the apostle executed in this city by Herod Agrippa I", ["Acts 12:1-2"]),
        "paul": ("seized in the temple here and arrested by the Roman guard", ["Acts 21:27-33"]),
    },
}
